"""initial

Revision ID: b3320398c202
Revises: 
Create Date: 2026-01-22 10:31:11.235757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3320398c202'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('webhook_events', 'processed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('webhook_events', 'updated_at')
    # ### end Alembic commands ###
